export const FPS = 24;
export const AnimationState = {
  Idle: 'idle',
  Play: 'play',
};
export const FRAMES = [
  'frame23.png',
  'frame28.png',
  'frame33.png',
  'frame38.png',
  'frame43.png',
  'frame48.png',
  'frame53.png',
  'frame58.png',
  'frame63.png',
  'frame68.png',
  'frame73.png',
  'frame78.png',
  'frame83.png',
  'frame88.png',
  'frame93.png',
  'frame98.png',
  'frame103.png',
  'frame108.png',
  'frame113.png',
  'frame2.png',
  'frame7.png',
  'frame12.png',
  'frame17.png',
  'frame22.png',
];
